import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`flex min-h-screen flex-col bg-emerald-50 ${inter.className}`}
      >
        <header className="w-full h-16 sm:h-20 fixed text-emerald-500 font-bold bg-transparent border-b border-emerald-200 text-xl sm:text-2xl xl:text-3xl backdrop-blur-2xl">
          <div className="flex h-16 sm:h-20 items-center px-5 xl:px-0 max-w-6xl mx-auto">HEADER</div>
        </header>
        <main className="flex-1 mt-16 sm:mt-20">{children}</main>
        <footer className="h-16 flex items-center justify-center text-white bg-emerald-500 text-sm">
          footer
        </footer>
      </body>
    </html>
  );
}
